### ISSUE TITLE
Still can not understand why set two task: document ranking and passage ranking.

### ISSUE THREAD

**Issue by guotong1988** [microsoft/TREC-2019-Deep-Learning#8]
I am new to text retrieval. The two tasks seems are similar.
Thank you very much.

**Comment by spacemanidol** [comment]
The tasks are very similair by design. We have document and passage retrieval to explore how systems scale across document size and with sparcity of labels. Since all relevance labels are on the passage data, any learned methods would be using transfer learning in the document task. We also believe that the passage ranking task is likley easier since it is more simple to set up(and there is already code in methods in the msmarco task) and thus provided the contestants with a tasks with different difficulty.
